version: "3"
services:
  app:
    build: ./backend
    tty: true
    volumes:
      - .:/go/src/work
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: dockerMysql
    ports:
      - "3001:3306"
    environment:
      MYSQL_DATABASE: docker_go
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    command: mysqld

  nginx:
    build: nginx/.
    ports:
      - 80:80
    depends_on:
      - app
